### ISSUE TITLE
안녕하세요??

### ISSUE THREAD

**Issue by Choi-Eunseok** [NullFull/awesome-nCoV-korea#6]
안녕하세요?? 부산의 코로나 확진자들의 동선을 부산 공식 홈페이지에서 크롤링해서 지도에 마커를 찍어주는 사이트인 부산 코로나와(http://busancoronawa.kro.kr/)를 개발하고 있는 고3 최은석이라고 합니다. 부족한점은 많지만 이 사이트를 많은 부산지역주민들에게 알리고 싶어서 이 사이트에 등록을 요청해도 될까요?? 깃헙을 사용해본적이 없어서...PR은 어떻게 쓰는것인지 잘 모르겠네요...

**Comment by realsigridjin** [comment]
추가하였습니다. 감사합니다 :)
